const axios = require('axios');

const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL;

/**
 * Send status report to Slack
 */
async function sendToSlack(req, res, next) {
  try {
    const { productName, statusSummary, progress, doneTasks, totalTasks, nextSteps, launchChecklist } = req.body;

    // Validation
    if (!productName || !statusSummary) {
      return res.status(400).json({
        error: 'productName and statusSummary are required',
      });
    }

    if (!SLACK_WEBHOOK_URL) {
      return res.status(500).json({
        error: 'SLACK_WEBHOOK_URL is not configured',
      });
    }

    // Format the Slack message using Block Kit
    const message = {
      text: `📊 Product Update: ${productName}`,
      blocks: [
        {
          type: 'header',
          text: {
            type: 'plain_text',
            text: `📊 ${productName} - Status Update`,
            emoji: true,
          },
        },
        {
          type: 'section',
          fields: [
            {
              type: 'mrkdwn',
              text: `*Progress:*\n${progress}% complete`,
            },
            {
              type: 'mrkdwn',
              text: `*Tasks:*\n${doneTasks}/${totalTasks} done`,
            },
          ],
        },
        {
          type: 'divider',
        },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*📝 Status Summary*\n${statusSummary}`,
          },
        },
        {
          type: 'divider',
        },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*🎯 Next Steps*\n${nextSteps.map((s) => `• ${s}`).join('\n')}`,
          },
        },
        {
          type: 'divider',
        },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*✅ Launch Checklist*\n${launchChecklist
              .map((item) => {
                const icon =
                  item.status === 'complete'
                    ? '✅'
                    : item.status === 'in-progress'
                    ? '🔄'
                    : '⬜';
                return `${icon} ${item.item}`;
              })
              .join('\n')}`,
          },
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `_Generated by Lifecycle Copilot | ${new Date().toLocaleString()}_`,
            },
          ],
        },
      ],
    };

    // Send to Slack
    const response = await axios.post(SLACK_WEBHOOK_URL, message, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (response.status === 200) {
      res.json({ success: true, message: 'Sent to Slack' });
    } else {
      throw new Error(`Slack API returned status ${response.status}`);
    }
  } catch (error) {
    console.error('Error sending to Slack:', error);

    if (error.response) {
      // API error response
      const status = error.response.status;
      const message = error.response.data?.message || error.message;

      if (status === 404) {
        return res.status(404).json({
          error: 'Slack webhook not found. Please verify your webhook URL is correct.',
        });
      }

      return res.status(status).json({
        error: `Slack API error: ${message}`,
      });
    }

    if (error.message.includes('Invalid webhook URL')) {
      return res.status(400).json({
        error: 'Invalid Slack webhook URL. Please check your configuration.',
      });
    }

    next(error);
  }
}

module.exports = { sendToSlack };

