// Real API endpoint for sending status to Slack using Webhook

import { API_CONFIG } from '../config/api-keys';

interface SlackPayload {
  productName: string;
  statusSummary: string;
  progress: number;
  doneTasks: number;
  totalTasks: number;
  nextSteps: string[];
  launchChecklist: Array<{
    item: string;
    status: 'complete' | 'in-progress' | 'pending';
  }>;
}

export async function sendToSlack(payload: SlackPayload): Promise<void> {
  // Format the Slack message using Block Kit
  const message = {
    text: `📊 Product Update: ${payload.productName}`,
    blocks: [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `📊 ${payload.productName} - Status Update`,
          emoji: true
        }
      },
      {
        type: "section",
        fields: [
          {
            type: "mrkdwn",
            text: `*Progress:*\n${payload.progress}% complete`
          },
          {
            type: "mrkdwn",
            text: `*Tasks:*\n${payload.doneTasks}/${payload.totalTasks} done`
          }
        ]
      },
      {
        type: "divider"
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*📝 Status Summary*\n${payload.statusSummary}`
        }
      },
      {
        type: "divider"
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*🎯 Next Steps*\n${payload.nextSteps.map(s => `• ${s}`).join('\n')}`
        }
      },
      {
        type: "divider"
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*✅ Launch Checklist*\n${payload.launchChecklist.map(item => {
            const icon = item.status === 'complete' ? '✅' : item.status === 'in-progress' ? '🔄' : '⬜';
            return `${icon} ${item.item}`;
          }).join('\n')}`
        }
      },
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: `_Generated by Lifecycle Copilot | ${new Date().toLocaleString()}_`
          }
        ]
      }
    ]
  };

  try {
    const response = await fetch(API_CONFIG.SLACK_WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(message),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Slack API error: ${response.status} - ${errorText}`);
    }

    console.log('✅ Successfully sent message to Slack');
  } catch (error) {
    console.error('❌ Error sending to Slack:', error);
    
    // Provide helpful error messages
    if (error instanceof Error) {
      if (error.message.includes('Invalid webhook URL')) {
        throw new Error('Invalid Slack webhook URL. Please check your configuration in /config/api-keys.ts');
      }
      if (error.message.includes('404')) {
        throw new Error('Slack webhook not found. Please verify your webhook URL is correct.');
      }
      throw error;
    }
    
    throw new Error('Failed to send message to Slack. Please check your webhook URL.');
  }
}

// Example API route handler (Next.js format)
export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const payload = req.body as SlackPayload;
    await sendToSlack(payload);
    res.status(200).json({ success: true, message: 'Sent to Slack' });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to send to Slack';
    res.status(500).json({ error: message });
  }
}
